version: '3.7'

services:
  kinesis_aws:  
    container_name: kinesis_aws
    build: 
      context: ./producer
    volumes: 
      - ./producer/:/code 


  terraform: 
    image: hashicorp/terraform:latest
    volumes: 
      - ./:/infra
    working_dir: /infra
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
